# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Apps

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build TableIT.Core
        run: dotnet build --configuration Release --framework netstandard2.0 -p:TargetFramework=netstandard2.0
        working-directory: TableIT.Core

      - name: 'Build Functions App'
        run: dotnet build TableIT.Functions.csproj --configuration Release --output ../func-output
        working-directory: TableIT.Functions

      - name: Build Web App
        run: dotnet build --configuration Release
        working-directory: TableIT.Web

      - name: dotnet publish
        run: dotnet publish -c Release -o ../web-output
        working-directory: TableIT.Web

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'TableITFunctions'
          slot-name: 'Production'
          package: './func-output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FD23C6D2E7E545F6ADEB7A758CEFD59F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'tableit'
            slot-name: 'production'
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_307798C99CB54F0D8AC9892C475699EF }}
            package: ./web-output